### PR TITLE
Title: Created Unit test for Country

### PR DESCRIPTION
**Pull request by adeniranjohn**
[As assigned on Issue](https://github.com/fleencorp/fleen-feen/issues/42)

### CODE REVIEW

**Review by aalamu — CHANGES_REQUESTED** [review]
1. The test class name should be ```CountryTest``` instead of ```CountryTests```
2. The test method names should be in snake case
3. The test method names should follow the styles found in ```Oauth2AuthorizationTest``` and ```FleenFeenEntity```
4. You don't need a ```@BeforeEach``` at the moment, which means each method or ```@Test``` case method should instantiate a new Country class. 
5. Comments in the code should either indicate ```GIVEN``` or ```ASSERT```

**Comment by adeniranjohn** [comment]
@aalamu give a check if it addresses the above

**Review by aalamu — CHANGES_REQUESTED** [review]
1. We don't need the ```@EqualsAndHashCode``` for the moment.
2. We need to add a one line before the ```//ASSERT```
3. We need to improve the naming of our test cases ```@Test```
 For example:
- ```test_nullability``` can be renamed to ```ensure_country_is_null``` if we are checking if the ```country``` is null as in ```Country country = null```
- We can also rename ```nullCountry``` to ```country```
- We should write simple tests for each fields like ```ensure_country_title_is_not_null```, ```ensure_country_title_is_null```, ```ensure_country_titles_are_equal```, ```ensure_country_titles_are_not_equal```
4. We don't need two ```assertNotEquals``` in  ```test_inequality_with_other_object_types```. We can just test if country1 is not equal to country2.
5. We have ```assertNull``` method for checking if a value or object is null.

**Good job so far. We're doing this to employ the high standard so codes can align in the future.**

7. For the ID, we can just keep simple like ```1L``` or ```2L``` like when you create a new row in a **SQL table**

**Comment by aalamu** [comment]
> @aalamu Issues resolved

I'll go through it.

**Review by aalamu — CHANGES_REQUESTED** [review]
This is fantastic.

We need to improve our spacing between for example the name of the method and its opening brace like

```ensure_country_title_is_not_null(){```

to 

```ensure_country_title_is_not_null() {```

For how we create of instance of classes, let's try to make our method agnostic and independent of libraries like lombok. So instead of

```Country country = Country.builder()
.title()
.build()```

we can use

```Country country = new Country();
country.setTitle("Nigeria");
```

We should also close the extra empty line between

```//GIVEN```  and a method name. For example

```void ensure_country_objects_are_not_equal() {

        //GIVEN
```

should be

```void ensure_country_objects_are_not_equal() {
        //GIVEN
```

**Comment by adeniranjohn** [comment]
@aalamu 
It would be helpful if you could check all the errors and highlight them at once for correction.

**Comment by aalamu** [comment]
@adeniranjohn We cannot find all the problems at once, so we refactor one thing and then we find the next thing to refactor.

1. We need to push to ```feature/fleenfeen-24``` as indicated in the issue because each issue is linked to a branch for we to work on.
2. We need a better PR description for our implementation like

Title: Created Unit test for Country

### Description
Created unit test for Country

1. Ensured all test methods were refactored from camel case to snake case pattern
2. Changed from Lombok builder to simple Java Object instantation pattern to make test codes agnostic and independent of a third party library.

4.  If we are testing just an id in a ```@Test``` case, we can just write

```
Country country = new Country();
country.setCountryId(1L);
```

and then test for the assertion. We do not need to set other argument if we're testing them in a specific ```@Test``` case.

**Pull request closed without merging**
